service:
  golangci-lint-version: 1.50.0

run:
  tests: false
  skip-dirs:
    - generated
    - mocks
output:
  print-issued-lines: false

linters-settings:
  dupl:
    threshold: 100
  lll:
    line-length: 140
  goconst:
    min-len: 3
    min-occurrences: 3
  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental
  revive:
    rules:
      - name: context-keys-type
        disabled: true
  staticcheck:
    checks: ["all", "-SA1029"]

stylecheck:
  checks: ["-ST1003", "-ST1016", "-ST1020", "-ST1021", "-ST1022"]

linters:
  enable:
    - deadcode
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - unused
    - varcheck
    - bodyclose
    - depguard
    - exportloopref
    - goconst
    - gocritic
    - goimports
    - revive
    - nakedret
    - nestif
    - prealloc
    - sqlclosecheck
    - stylecheck
    - unconvert
    - unparam
#    - errname
#    - gosec

issues:
  exclude-use-default: false
  exclude:
    - G104
    - ST1000
    - ST1005
    - should check returned error before deferring
    - don't use an underscore in package name
    - Error return value of .((os\.)?std(out|err)\..*|.*Close|.*Flush|os\.Remove(All)?|.*printf?|os\.(Un)?Setenv|.*Rollback). is not checked
    - exported func * returns unexported type *, which can be annoying to use
    - exported type ([a-zA-Z'.*]*) should have comment or be unexported
    - (comment on exported (method|function|type|const)|should have( a package)? comment|comment should be of the form)
    - should have a package comment, unless it's in another file for this package
